/**
 * META ADS API INTEGRATION
  * Traffic Masters Squad — Agencia316/aiox-core
   *
    * Conecta à Meta Marketing API e busca métricas de campanhas
     * para análise pelo Claude Code com os agentes do Traffic Masters Squad.
      *
       * SETUP:
        * 1. Crie um App em developers.facebook.com
         * 2. Gere um Access Token com permissões: ads_read, ads_management
          * 3. Copie o Ad Account ID do Meta Business Manager
           * 4. Preencha o arquivo .env com as variáveis abaixo
            *
             * USO: node integrations/meta-ads.js
              */

              require('dotenv').config();
              const https = require('https');
              const fs = require('fs');

              // ─── CONFIGURAÇÃO ────────────────────────────────────────────────────────────
              const CONFIG = {
                accessToken: process.env.META_ACCESS_TOKEN,
                  adAccountId: process.env.META_AD_ACCOUNT_ID, // formato: act_XXXXXXXXX
                    apiVersion: 'v19.0',
                      dateRange: {
                          since: process.env.META_DATE_SINCE || getDateDaysAgo(30),
                              until: process.env.META_DATE_UNTIL || getDateDaysAgo(0),
                                },
                                };

                                // ─── HELPERS ─────────────────────────────────────────────────────────────────
                                function getDateDaysAgo(days) {
                                  const d = new Date();
                                    d.setDate(d.getDate() - days);
                                      return d.toISOString().split('T')[0];
                                      }

                                      function metaRequest(path) {
                                        return new Promise((resolve, reject) => {
                                            const url = `https://graph.facebook.com/${CONFIG.apiVersion}/${path}&access_token=${CONFIG.accessToken}`;
                                                https.get(url, (res) => {
                                                      let data = '';
                                                            res.on('data', (chunk) => (data += chunk));
                                                                  res.on('end', () => {
                                                                          try {
                                                                                    resolve(JSON.parse(data));
                                                                                            } catch (e) {
                                                                                                      reject(e);
                                                                                                              }
                                                                                                                    });
                                                                                                                        }).on('error', reject);
                                                                                                                          });
                                                                                                                          }
                                                                                                                          
                                                                                                                          // ─── FUNÇÕES PRINCIPAIS ───────────────────────────────────────────────────────
                                                                                                                          
                                                                                                                          // Busca overview da conta
                                                                                                                          async function getAccountOverview() {
                                                                                                                            const fields = 'name,account_status,currency,timezone_name,spend_cap,amount_spent';
                                                                                                                              const data = await metaRequest(`${CONFIG.adAccountId}?fields=${fields}`);
                                                                                                                                return data;
                                                                                                                                }
                                                                                                                                
                                                                                                                                // Busca campanhas ativas com métricas
                                                                                                                                async function getCampaigns() {
                                                                                                                                  const fields = 'id,name,status,objective,daily_budget,lifetime_budget';
                                                                                                                                    const data = await metaRequest(`${CONFIG.adAccountId}/campaigns?fields=${fields}&limit=50`);
                                                                                                                                      return data.data || [];
                                                                                                                                      }
                                                                                                                                      
                                                                                                                                      // Busca insights de performance (principais métricas)
                                                                                                                                      async function getAccountInsights() {
                                                                                                                                        const fields = [
                                                                                                                                            'spend',
                                                                                                                                                'impressions',
                                                                                                                                                    'reach',
                                                                                                                                                        'clicks',
                                                                                                                                                            'ctr',
                                                                                                                                                                'cpc',
                                                                                                                                                                    'cpm',
                                                                                                                                                                        'cpp',
                                                                                                                                                                            'actions',
                                                                                                                                                                                'action_values',
                                                                                                                                                                                    'cost_per_action_type',
                                                                                                                                                                                        'purchase_roas',
                                                                                                                                                                                            'frequency',
                                                                                                                                                                                                'unique_clicks',
                                                                                                                                                                                                    'unique_ctr',
                                                                                                                                                                                                      ].join(',');
                                                                                                                                                                                                      
                                                                                                                                                                                                        const datePreset = `time_range={"since":"${CONFIG.dateRange.since}","until":"${CONFIG.dateRange.until}"}`;
                                                                                                                                                                                                          const data = await metaRequest(`${CONFIG.adAccountId}/insights?fields=${fields}&${datePreset}`);
                                                                                                                                                                                                            return data.data || [];
                                                                                                                                                                                                            }
                                                                                                                                                                                                            
                                                                                                                                                                                                            // Busca insights por campanha
                                                                                                                                                                                                            async function getCampaignInsights() {
                                                                                                                                                                                                              const fields = [
                                                                                                                                                                                                                  'campaign_name',
                                                                                                                                                                                                                      'campaign_id',
                                                                                                                                                                                                                          'spend',
                                                                                                                                                                                                                              'impressions',
                                                                                                                                                                                                                                  'clicks',
                                                                                                                                                                                                                                      'ctr',
                                                                                                                                                                                                                                          'cpc',
                                                                                                                                                                                                                                              'cpm',
                                                                                                                                                                                                                                                  'actions',
                                                                                                                                                                                                                                                      'purchase_roas',
                                                                                                                                                                                                                                                          'cost_per_action_type',
                                                                                                                                                                                                                                                            ].join(',');
                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                              const datePreset = `time_range={"since":"${CONFIG.dateRange.since}","until":"${CONFIG.dateRange.until}"}`;
                                                                                                                                                                                                                                                                const data = await metaRequest(
                                                                                                                                                                                                                                                                    `${CONFIG.adAccountId}/insights?fields=${fields}&level=campaign&${datePreset}&limit=50`
                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                        return data.data || [];
                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                        // Busca top anúncios por performance
                                                                                                                                                                                                                                                                        async function getTopAds() {
                                                                                                                                                                                                                                                                          const fields = [
                                                                                                                                                                                                                                                                              'ad_name',
                                                                                                                                                                                                                                                                                  'ad_id',
                                                                                                                                                                                                                                                                                      'adset_name',
                                                                                                                                                                                                                                                                                          'campaign_name',
                                                                                                                                                                                                                                                                                              'spend',
                                                                                                                                                                                                                                                                                                  'impressions',
                                                                                                                                                                                                                                                                                                      'clicks',
                                                                                                                                                                                                                                                                                                          'ctr',
                                                                                                                                                                                                                                                                                                              'cpc',
                                                                                                                                                                                                                                                                                                                  'actions',
                                                                                                                                                                                                                                                                                                                      'purchase_roas',
                                                                                                                                                                                                                                                                                                                        ].join(',');
                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                          const datePreset = `time_range={"since":"${CONFIG.dateRange.since}","until":"${CONFIG.dateRange.until}"}`;
                                                                                                                                                                                                                                                                                                                            const data = await metaRequest(
                                                                                                                                                                                                                                                                                                                                `${CONFIG.adAccountId}/insights?fields=${fields}&level=ad&${datePreset}&limit=20&sort=["spend_descending"]`
                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                    return data.data || [];
                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                    // ─── RELATÓRIO PARA O CLAUDE ──────────────────────────────────────────────────
                                                                                                                                                                                                                                                                                                                                    function formatForClaude(account, insights, campaigns, campaignInsights, topAds) {
                                                                                                                                                                                                                                                                                                                                      const report = {
                                                                                                                                                                                                                                                                                                                                          generated_at: new Date().toISOString(),
                                                                                                                                                                                                                                                                                                                                              period: CONFIG.dateRange,
                                                                                                                                                                                                                                                                                                                                                  platform: 'Meta Ads (Facebook/Instagram)',
                                                                                                                                                                                                                                                                                                                                                      account: {
                                                                                                                                                                                                                                                                                                                                                            name: account.name,
                                                                                                                                                                                                                                                                                                                                                                  currency: account.currency,
                                                                                                                                                                                                                                                                                                                                                                        timezone: account.timezone_name,
                                                                                                                                                                                                                                                                                                                                                                              total_spent: insights[0]?.spend || '0',
                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                      account_performance: insights[0] || {},
                                                                                                                                                                                                                                                                                                                                                                                          active_campaigns: campaigns.filter((c) => c.status === 'ACTIVE').length,
                                                                                                                                                                                                                                                                                                                                                                                              total_campaigns: campaigns.length,
                                                                                                                                                                                                                                                                                                                                                                                                  campaign_breakdown: campaignInsights,
                                                                                                                                                                                                                                                                                                                                                                                                      top_ads_by_spend: topAds.slice(0, 10),
                                                                                                                                                                                                                                                                                                                                                                                                          summary_for_analysis: {
                                                                                                                                                                                                                                                                                                                                                                                                                total_spend: insights[0]?.spend || '0',
                                                                                                                                                                                                                                                                                                                                                                                                                      total_impressions: insights[0]?.impressions || '0',
                                                                                                                                                                                                                                                                                                                                                                                                                            total_clicks: insights[0]?.clicks || '0',
                                                                                                                                                                                                                                                                                                                                                                                                                                  average_ctr: insights[0]?.ctr || '0',
                                                                                                                                                                                                                                                                                                                                                                                                                                        average_cpc: insights[0]?.cpc || '0',
                                                                                                                                                                                                                                                                                                                                                                                                                                              average_cpm: insights[0]?.cpm || '0',
                                                                                                                                                                                                                                                                                                                                                                                                                                                    purchase_roas: insights[0]?.purchase_roas?.[0]?.value || 'N/A',
                                                                                                                                                                                                                                                                                                                                                                                                                                                          frequency: insights[0]?.frequency || '0',
                                                                                                                                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return report;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // ─── MAIN ─────────────────────────────────────────────────────────────────────
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  async function main() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (!CONFIG.accessToken || !CONFIG.adAccountId) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        console.error('❌ ERRO: Configure META_ACCESS_TOKEN e META_AD_ACCOUNT_ID no arquivo .env');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.log('\nVariáveis necessárias no .env:');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.log('META_ACCESS_TOKEN=seu_token_aqui');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.log('META_AD_ACCOUNT_ID=act_seu_id_aqui');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        console.log('META_DATE_SINCE=2024-01-01 (opcional)');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.log('META_DATE_UNTIL=2024-01-31 (opcional)');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                process.exit(1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.log('🔄 Conectando à Meta Marketing API...');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.log(`📅 Período: ${CONFIG.dateRange.since} → ${CONFIG.dateRange.until}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        console.log(`📊 Conta: ${CONFIG.adAccountId}\n`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const [account, insights, campaigns, campaignInsights, topAds] = await Promise.all([
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    getAccountOverview(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          getAccountInsights(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                getCampaigns(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      getCampaignInsights(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            getTopAds(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const report = formatForClaude(account, insights, campaigns, campaignInsights, topAds);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Salva o relatório em JSON para uso pelo Claude Code
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const outputPath = 'integrations/reports/meta-ads-report.json';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (!fs.existsSync('integrations/reports')) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fs.mkdirSync('integrations/reports', { recursive: true });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              fs.writeFileSync(outputPath, JSON.stringify(report, null, 2));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  console.log('✅ Relatório Meta Ads gerado com sucesso!');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.log(`📁 Arquivo: ${outputPath}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          console.log('\n📊 RESUMO:');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              console.log(`   💰 Total Gasto: ${report.account.currency} ${report.summary_for_analysis.total_spend}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  console.log(`   👁️  Impressões: ${report.summary_for_analysis.total_impressions}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.log(`   🖱️  Cliques: ${report.summary_for_analysis.total_clicks}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          console.log(`   📈 CTR Médio: ${report.summary_for_analysis.average_ctr}%`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              console.log(`   💵 CPC Médio: ${report.summary_for_analysis.average_cpc}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  console.log(`   🎯 ROAS: ${report.summary_for_analysis.purchase_roas}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.log(`   📣 Campanhas Ativas: ${report.active_campaigns}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          console.log('\n🤖 Agora rode no Claude Code:');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              console.log('   @traffic-chief *diagnose');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  console.log('   ou');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.log('   @performance-analyst *analyze-data');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.error('❌ Erro ao buscar dados da Meta API:', error.message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (error.message.includes('190')) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.log('⚠️  Token inválido ou expirado. Gere um novo em: developers.facebook.com');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            main();
